DROP FOREIGN TABLE IF EXISTS o_det;
CREATE FOREIGN TABLE o_det
( id bigint NOT NULL,
  count_info_id bigint,
  count_time timestamp without time zone,
  n_cars_r bigint,
  n_cars_t bigint,
  n_cars_l bigint,
  s_cars_r bigint,
  s_cars_t bigint,
  s_cars_l bigint,
  e_cars_r bigint,
  e_cars_t bigint,
  e_cars_l bigint,
  w_cars_r bigint,
  w_cars_t bigint,
  w_cars_l bigint,
  n_truck_r bigint,
  n_truck_t bigint,
  n_truck_l bigint,
  s_truck_r bigint,
  s_truck_t bigint,
  s_truck_l bigint,
  e_truck_r bigint,
  e_truck_t bigint,
  e_truck_l bigint,
  w_truck_r bigint,
  w_truck_t bigint,
  w_truck_l bigint,
  n_bus_r bigint,
  n_bus_t bigint,
  n_bus_l bigint,
  s_bus_r bigint,
  s_bus_t bigint,
  s_bus_l bigint,
  e_bus_r bigint,
  e_bus_t bigint,
  e_bus_l bigint,
  w_bus_r bigint,
  w_bus_t bigint,
  w_bus_l bigint,
  n_peds bigint,
  s_peds bigint,
  e_peds bigint,
  w_peds bigint,
  n_bike bigint,
  s_bike bigint,
  e_bike bigint,
  w_bike bigint,
  n_other bigint,
  s_other bigint,
  e_other bigint,
  w_other bigint) SERVER oradb OPTIONS (table 'DET');